language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
bundler_args: --jobs=2
before_script:
  - mysql -e 'create database mlborder_test;'
  - cp ./.travis.database.yml ./config/database.yml
script:
  - bundle exec rake db:create:all
  - bundle exec rspec
